function plot_integrator_compare(filename)
    % Plot the comparisons generated by integrator compare
    % 10 July 2017
    close all
    load(filename);
    t0 = 0;
    tf = 200; % figure out how to dimensionalize time
    set(0,'DefaultAxesFontSize',22);

    e_fig = figure('PaperPositionMode','auto'); % energy history
    h_fig = figure('PaperPositionMode', 'auto'); % mean \Delta E
    t_fig = figure('PaperPositionMode', 'auto'); % cpu time
    c_fig = figure('PaperPositionMode', 'auto'); % cpu time vs E

    % now plot the same things vs number of steps
    hn_fig = figure('PaperPositionMode', 'auto'); % mean \Delta E
    tn_fig = figure('PaperPositionMode', 'auto'); % cpu time

    markersize = 10;
    linewidth = 2;
    % add to plot
    % loop over the changes in the number of steps/step size
    for ii = 1:length(num_steps)
        ns = num_steps(ii);
        t_vec = linspace(t0, tf, ns);
        h = (tf - t0) / ns;
        if ii == 1
            % plot vs step size
            set(0,'CurrentFigure',e_fig)
            semilogy(t_vec(1:1000:end), abs(Ehist_ode45(ii,1:ns/1000)-Ehist_ode45(ii,1)), 'r', 'DisplayName', 'ODE45')
            hold all
            % semilogy(t_vec(1:1000:end), abs(Ehist_ode4(ii,1:ns/1000) - Ehist_ode4(ii,1)), 'b','DisplayName', 'RK4')
            semilogy(t_vec(1:1000:end), abs(Ehist_trap(ii,1:ns/1000)-Ehist_trap(ii,1)), 'g', 'DisplayName', 'VI')

            set(0, 'CurrentFigure', h_fig)
            loglog(h, mean(abs(Ehist_ode45(ii,ns/1000) - Ehist_ode45(ii,1))), 'ro', 'DisplayName', 'ODE45', 'MarkerSize', markersize, 'Linewidth', linewidth)
            hold all
            % loglog(h, mean(abs(Ehist_ode4(ii,1:ns/1000) - Ehist_ode4(ii,1))), 'bs', 'DisplayName', 'RK4')
            loglog(h, mean(abs(Ehist_trap(ii,ns/1000) - Ehist_trap(ii,1))), 'gx', 'DisplayName', 'VI', 'MarkerSize', markersize, 'Linewidth', linewidth)

            set(0, 'CurrentFigure', t_fig)
            loglog(h, cputime_ode45(ii), 'ro', 'DisplayName', 'ODE45', 'MarkerSize', markersize, 'Linewidth', linewidth)
            hold all
            % loglog(h, cputime_ode4(ii), 'bs', 'DisplayName', 'RK4')
            loglog(h, cputime_trap(ii), 'gx', 'DisplayName', 'VI', 'MarkerSize', markersize, 'Linewidth', linewidth)

            set(0, 'CurrentFigure', c_fig)
            loglog(cputime_ode45(ii), mean(abs(Ehist_ode45(ii,1:ns/1000) - Ehist_ode45(ii,1))), 'ro', 'DisplayName', 'ODE45', 'MarkerSize', markersize, 'Linewidth', linewidth)
            hold all
            % loglog(cputime_ode4(ii), mean(abs(Ehist_ode4(ii,1:ns/1000) - Ehist_ode4(ii,1))), 'bs', 'DisplayName', 'RK4')
            loglog(cputime_trap(ii), mean(abs(Ehist_trap(ii,1:ns/1000) - Ehist_trap(ii,1))), 'gx', 'DisplayName', 'VI', 'MarkerSize', markersize, 'Linewidth', linewidth)
            
            %% plot vs number of steps
            set(0, 'CurrentFigure', hn_fig)
            loglog(ns, mean(abs(Ehist_ode45(ii,ns/1000) - Ehist_ode45(ii,1))), 'ro', 'DisplayName', 'ODE45', 'MarkerSize', markersize, 'Linewidth', linewidth)
            hold all
            % loglog(ns, mean(abs(Ehist_ode4(ii,ns/1000) - Ehist_ode4(ii,1))), 'bs', 'DisplayName', 'RK4')
            loglog(ns, mean(abs(Ehist_trap(ii,ns/1000) - Ehist_trap(ii,1))), 'gx', 'DisplayName', 'VI', 'MarkerSize', markersize, 'Linewidth', linewidth)

            set(0, 'CurrentFigure', tn_fig)
            loglog(ns, cputime_ode45(ii), 'ro', 'DisplayName', 'ODE45', 'MarkerSize', markersize, 'Linewidth', linewidth)
            hold all
            % loglog(ns, cputime_ode4(ii), 'bs', 'DisplayName', 'RK4')
            loglog(ns, cputime_trap(ii), 'gx', 'DisplayName', 'VI', 'MarkerSize', markersize, 'Linewidth', linewidth)

        else
            set(0,'CurrentFigure',e_fig)
            semilogy(t_vec(1:1000:end), abs(Ehist_ode45(ii,1:ns/1000)-Ehist_ode45(ii,1)), 'r', 'DisplayName', 'ODE45', 'HandleVisibility', 'off')
            % semilogy(t_vec(1:1000:end), abs(Ehist_ode4(ii,1:ns/1000) - Ehist_ode4(ii,1)), 'b','DisplayName', 'RK4', 'HandleVisibility', 'off')
            semilogy(t_vec(1:1000:end), abs(Ehist_trap(ii,1:ns/1000)-Ehist_trap(ii,1)), 'g', 'DisplayName', 'VI', 'HandleVisibility', 'off')

            set(0, 'CurrentFigure', h_fig)
            loglog(h, mean(abs(Ehist_ode45(ii,ns/1000) - Ehist_ode45(ii,1))), 'ro', 'DisplayName', 'ODE45', 'HandleVisibility', 'off', 'MarkerSize', markersize, 'Linewidth', linewidth)
            % loglog(h, mean(abs(Ehist_ode4(ii,ns/1000) - Ehist_ode4(ii,1))), 'bs', 'DisplayName', 'RK4', 'HandleVisibility', 'off')
            loglog(h, mean(abs(Ehist_trap(ii,ns/1000) - Ehist_trap(ii,1))), 'gx', 'DisplayName', 'VI', 'HandleVisibility', 'off', 'MarkerSize', markersize, 'Linewidth', linewidth)

            set(0, 'CurrentFigure', t_fig)
            loglog(h, cputime_ode45(ii), 'ro', 'DisplayName', 'ODE45', 'HandleVisibility', 'off', 'MarkerSize', markersize, 'Linewidth', linewidth)
            % loglog(h, cputime_ode4(ii), 'bs', 'DisplayName', 'RK4', 'HandleVisibility', 'off')
            loglog(h, cputime_trap(ii), 'gx', 'DisplayName', 'VI', 'HandleVisibility', 'off', 'MarkerSize', markersize, 'Linewidth', linewidth)

            set(0, 'CurrentFigure', c_fig)
            loglog(cputime_ode45(ii), mean(abs(Ehist_ode45(ii,1:ns/1000) - Ehist_ode45(ii,1))), 'ro', 'DisplayName', 'ODE45', 'HandleVisibility', 'off', 'MarkerSize', markersize, 'Linewidth', linewidth)
            % loglog(cputime_ode4(ii), mean(abs(Ehist_ode4(ii,1:ns/1000) - Ehist_ode4(ii,1))), 'bs', 'DisplayName', 'RK4', 'HandleVisibility', 'off')
            loglog(cputime_trap(ii), mean(abs(Ehist_trap(ii,1:ns/1000) - Ehist_trap(ii,1))), 'gx', 'DisplayName', 'VI', 'HandleVisibility', 'off', 'MarkerSize', markersize, 'Linewidth', linewidth)

            %% plot vs number of steps
            set(0, 'CurrentFigure', hn_fig)
            loglog(ns, mean(abs(Ehist_ode45(ii,ns/1000) - Ehist_ode45(ii,1))), 'ro', 'DisplayName', 'ODE45', 'HandleVisibility', 'off', 'MarkerSize', markersize, 'Linewidth', linewidth)
            % loglog(ns, mean(abs(Ehist_odns/1000) - Ehist_ode4(ii,1))), 'bs', 'DisplayName', 'RK4')
            loglog(ns, mean(abs(Ehist_trap(ii,ns/1000) - Ehist_trap(ii,1))), 'gx', 'DisplayName', 'VI', 'HandleVisibility', 'off', 'MarkerSize', markersize, 'Linewidth', linewidth)

            set(0, 'CurrentFigure', tn_fig)
            loglog(ns, cputime_ode45(ii), 'ro', 'DisplayName', 'ODE45', 'HandleVisibility', 'off', 'MarkerSize', markersize, 'Linewidth', linewidth)
            hold all
            % loglog(ns, cputime_ode4(ii), 'bs', 'DisplayName', 'RK4')
            loglog(ns, cputime_trap(ii), 'gx', 'DisplayName', 'VI', 'HandleVisibility', 'off', 'Markersize', markersize, 'Linewidth', linewidth)

        end

    end
    set(0,'CurrentFigure',e_fig)
    grid on
    xlabel('$t$ (nondim) ','interpreter','latex','FontUnits','points','FontSize',22,'FontName','Times')
    ylabel('$ \Delta E$','interpreter','latex','FontUnits','points','FontSize',22,'FontName','Times')
    e_legend = legend('show');

    set(0, 'CurrentFigure', h_fig)
    grid on 
    xlabel('$h$ (nondim)','interpreter','latex','FontUnits','points','FontSize',22,'FontName','Times')
    ylabel('Mean $ \Delta E$','interpreter','latex','FontUnits','points','FontSize',22,'FontName','Times')
    h_legend = legend('show');

    set(0, 'CurrentFigure', t_fig)
    grid on
    xlabel('$h$ (nondim)', 'interpreter', 'latex', 'FontUnits', 'points', 'FontSize', 22, 'FontName', 'Times')
    ylabel('CPU Time (sec)', 'interpreter', 'latex', 'FontUnits', 'points', 'FontSize', 22, 'FontName', 'Times')
    t_legend = legend('show');

    set(0, 'CurrentFigure', c_fig)
    grid on
    xlabel('CPU Time (sec)', 'interpreter', 'latex', 'FontUnits', 'points', 'FontSize', 22, 'FontName', 'Times')
    ylabel('Mean $ \Delta E$', 'interpreter', 'latex', 'FontUnits', 'points', 'FontSize', 22, 'FontName', 'Times')
    c_legend = legend('show');

    set(0, 'CurrentFigure', hn_fig)
    grid on 
    xlabel('Number of steps $n$ (nondim)','interpreter','latex','FontUnits','points','FontSize',22,'FontName','Times')
    ylabel('Mean $ \Delta E$','interpreter','latex','FontUnits','points','FontSize',22,'FontName','Times')
    hn_legend = legend('show');

    set(0, 'CurrentFigure', tn_fig)
    grid on
    xlabel('Number of steps $n$ (nondim)', 'interpreter', 'latex', 'FontUnits', 'points', 'FontSize', 22, 'FontName', 'Times')
    ylabel('CPU Time (sec)', 'interpreter', 'latex', 'FontUnits', 'points', 'FontSize', 22, 'FontName', 'Times')
    tn_legend = legend('show');

    set(e_legend,'interpreter','latex','FontUnits','points','FontSize',22,'FontName','Times');
    set(h_legend,'interpreter','latex','FontUnits','points','FontSize',22,'FontName','Times');
    set(t_legend,'interpreter','latex','FontUnits','points','FontSize',22,'FontName','Times');
    set(c_legend,'interpreter','latex','FontUnits','points','FontSize',22,'FontName','Times');

    set(hn_legend,'interpreter','latex','FontUnits','points','FontSize',22,'FontName','Times');
    set(tn_legend,'interpreter','latex','FontUnits','points','FontSize',22,'FontName','Times');
    % print(e_fig,'-dpsc2', 'energy.eps')
    % print(traj_fig,'-dpsc2', 'trajectory.eps')
    % print(comp_fig,'-dpsc2', 'components.eps')

    % print(e_fig,sprintf('./variational_integrator/energy_diff_h1%s%d.eps','e',step_exp))
    % print(traj_fig,sprintf('./variational_integrator/trajectory_h1%s%d.eps','e',step_exp))
    % print(comp_fig,sprintf('./variational_integrator/state_comp_h1%s%d.eps','e',step_exp))
